targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator: # for @RoutePage
        generate_for:
          - lib/ui/**_view.dart
      auto_route_generator:auto_router_generator: # for @AutoRouterConfig
        generate_for:
          - lib/app_router.dart